### ISSUE TITLE
哪里可以获取完整源码呢

### ISSUE THREAD

**Issue by SiMaLaoShi** [qmcloud/movehouse#1]

**Comment by qmcloud** [comment]
添加微信：BCFind5或者qq407193275

**Comment by IceCoffee2011** [comment]
别问了都是要钱的，国内很多项目打着开源的旗号，骗你加vx，再收费

**Comment by qmcloud** [comment]
> 别问了都是要钱的，国内很多项目打着开源的旗号，骗你加vx，再收费

这话说的，没能让你白嫖上就是骗子呗，你可以自己搞一套开源的代码，把链接粘贴到这些人的issuse里面，狠狠的扇扇这些人的脸。

**Comment by IceCoffee2011** [comment]
> > 别问了都是要钱的，国内很多项目打着开源的旗号，骗你加vx，再收费
> 
> 这话说的，没能让你白嫖上就是骗子呗，你可以自己搞一套开源的代码，把链接粘贴到这些人的issuse里面，狠狠的扇扇这些人的脸。

都是成年人，拜托，真要开源，你留个联系方式干嘛，明眼人谁不知道你想收费，既然收费就不要打者开源的旗号，也就欺负小白不懂，还白嫖，白嫖也不嫖你这个代码，呵呵

**Comment by qmcloud** [comment]
> > > 别问了都是要钱的，国内很多项目打着开源的旗号，骗你加vx，再收费
> > 
> > 
> > 这话说的，没能让你白嫖上就是骗子呗，你可以自己搞一套开源的代码，把链接粘贴到这些人的issuse里面，狠狠的扇扇这些人的脸。
> 
> 都是成年人，拜托，真要开源，你留个联系方式干嘛，明眼人谁不知道你想收费，既然收费就不要打者开源的旗号，也就欺负小白不懂，还白嫖，白嫖也不嫖你这个代码，呵呵

我死乞白赖的求你嫖我代码了？就我真开源了你敢商用一样，笑死，开源不是免费。没经历过这社会的毒打都，天天只会发这些没意义的东西有啥意思。
